Add comleted project
NikolenkoAnton/KPZ-PI-318-SUBGROUP_2 pull request #11
Opened 2019-10-29 09:37 UTC by sashaffg

2019-10-29 10:54 UTC, ghost requested changes
1) с английского языка слово Bill переводится как товарный чек. Слово Счет переводится как Account
2) ваши методы репозиториев и менеджеров должны возвращать конкретные типы, а не строки, потому что код-потребитель понятия не имеет как эти строки обрабатывать, а вы это не задокументировали. У нас же все таки ООП :)

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Controllers/BillsController.cs
> +        public ActionResult<string> GetAvaliableBillsList()
почему бы не возвращать список типа string. Возврат строки делает код клиента более сложным, заставляя парсить ответ, так же ваш клиент сломается если вы поменяете метод формирования строки

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Controllers/BillsController.cs
> +            for (int i = 0; i <  _valuesManager.GetAllBillsList().ToList().Count(); i++)
замечание выше применимо и к этому методу

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Models/Bill.cs
> +
лишняя новая строка

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Models/Bill.cs
> +        public bool GetIsBlocked()
1) метод Get не должен менять состояние
2) этот метод должен быть перенесен в manager

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Models/Bill.cs
> +        public void SetIsBlocked(bool Block)
это метод лишний, так как IsBlocked свойство этого класса доступно для записи (присутствует set)

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Repositories/BillRepository.cs
> +        //костыль в виде статика чтобы сохранялись изменения после пост запроса
это не костыль а текущая реализация :)

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Repositories/BillRepository.cs
> +    public class BillRepository : IBillsRepository, ITransientDependency
BillRepository => InMemoryBillRepository

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Repositories/BillRepository.cs
> +            //TODO out of boundary exception
TODO не должны присутствовать в пулл реквестах

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Repositories/BillRepository.cs
> +        public IEnumerable<string> GetAllBillsList()
почему просто не возвращать список обьектов типа Bill ?

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Repositories/BillRepository.cs
> +        public IEnumerable<string> GetActiveBillsList()
почему просто не возвращать список обьектов типа Bill ?

2019-10-29 10:54 UTC, anton-beetroot-23071996 commented on App.Bills/Services/ValidateServices.cs
> +            if (bill.GetIsBlocked())
счет разве не может быть заблокированным ?

2019-10-31 10:32 UTC, sashaffg commented on App.Bills/Repositories/BillRepository.cs
> +    public class BillRepository : IBillsRepository, ITransientDependency
Still actual

2019-10-31 10:35 UTC, sashaffg commented on App.Bills/Services/BillsManager.cs
> +            foreach(Bill bill in _repository.GetAllBillsList())
1. make isBocked readonly calculated property
2. check should not modify data

2019-11-01 19:47 UTC, ghost requested changes
ожидаю внесения оговоренных ранее изменений

2019-11-01 19:48 UTC, anton-beetroot-23071996 commented
Также, разрешите, пожалуйста, merge конфликты

2019-11-06 20:12 UTC, ghost approved these changes

2019-11-06 20:12 UTC, merged