add StockExceptionFilter
NikolenkoAnton/KPZ-PI-318-SUBGROUP_2 pull request #12
Opened 2019-10-30 19:46 UTC by NikolenkoAnton

2019-10-31 09:53 UTC, NikolenkoAnton commented on App.Stocks/Exceptions/IncorrectDateFormat.cs
> +    public class IncorrectParamsFormat : Exception
exception classes should end with "Exception"

2019-10-31 09:58 UTC, anton-cheg commented on App.Stocks/Filters/StockExceptionFilter.cs
> +                        if (entityType.Equals(typeof(Company)))
entity not found exception should contain info about identifier, used to search this type of entity

2019-10-31 10:05 UTC, anton-cheg commented on App.Stocks/Filters/StockExceptionFilter.cs
> +                case IncorrectStockDate incorrectStockDate:
each 'case' should correspind to one status code returned. 404 - EntityNotExistException. 400 - IncorrectParameterException. Too many case statements for the same or similar exception types

2019-10-31 10:09 UTC, NikolenkoAnton commented on App.Stocks/Filters/StockExceptionFilter.cs
> +                        logger.LogWarning($"Method: {context.Exception.TargetSite}.");
logWarning => logError

2019-11-01 19:45 UTC, ghost requested changes
ожидаю внесения оговоренных изменений

2019-11-02 05:52 UTC, NikolenkoAnton commented
> ожидаю внесения оговоренных изменений

Правки внесены

2019-11-02 06:59 UTC, ghost approved these changes

2019-11-02 06:59 UTC, merged