Deposits
NikolenkoAnton/KPZ-PI-318-SUBGROUP_2 pull request #8
Opened 2019-10-11 09:17 UTC by DmitryOzzmos

Done task for deposits

2019-10-14 16:32 UTC, anton-cheg reviewed
Nice try, Dmitriy

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/DepositsManager.cs
> +                Id = GetLastDepositID(),
Incorrect method

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/DepositsManager.cs
> +        IEnumerable<Deposit> GetAllDeposits();
Missing empty line between lines

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/DepositsManager.cs
> +            return depositsRepository.GetAllDeposit();
Use one style for return value from method( or => or return)

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/DepositsManager.cs
> +            int daysAmount = (finishDate - DateTime.Now).Days;
use var when variables type is obvious from rigth part expressions

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/DepositsManager.cs
> +            decimal sum = startSum + startSum * deposit.InterastRate * daysAmount / 365;
use var when variables type is obvious from rigth part expressions

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/Models/CreatedDepositDTO.cs
> +        public string Name { get; set; }
missing empty line

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/Models/Deposit.cs
> +        public decimal InterastRate { get; set; }
Missing empty lines

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/Repositories/InMemmoryDepositsRepository.cs
> +
excess empty lines

2019-10-14 16:32 UTC, NikolenkoAnton commented on App.Deposits/Repositories/InMemmoryDepositsRepository.cs
> +        public Deposit GetDepositById(int id) => deposits.Where(x => x.Id == id).FirstOrDefault();
Use one style for return value from method( or => or return)

2019-10-17 08:43 UTC, DmitryOzzmos commented on App.TestModule/App.Example.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.0" />
revert

2019-10-17 08:43 UTC, DmytroOzzmos commented on App.Web/App.Web.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
revert

2019-10-19 15:21 UTC, ghost requested changes
Please, address comments and re-request review

2019-10-27 11:12 UTC, ghost approved these changes

2019-10-27 11:15 UTC, merged